version: 2

jobs:
  build:
    docker:
      - image: johnnyshrewd/cli:1
    working_directory: ~/cko_wp
    steps:
      - checkout
      - run:
          name: Refresh Wordpress and Install Checkout
          command: |
            sudo unlink "/usr/lib/apache2/modules/libphp7.0.so"
            sudo apt-get install libapache2-mod-php
            sudo a2enmod php7.0
            sudo a2enmod rewrite && sudo /etc/init.d/apache2 restart && sudo service mysql restart
            cd /var/www/html/wordpress/wp-content/plugins/ && sudo mv ~/cko_wp/woocommerce-checkout-non-pci-gateway . && sudo mv ~/cko_wp/woocommerce-checkout-pci-gateway . && sudo chmod -R 777 .
      - run:
          name: Install dependencies
          command: |
            cd ~/cko_wp/tests && npm i 
      - run:
          name: Run Tests
          command: |
            cd ~/cko_wp/tests && ./node_modules/.bin/chimp config/chimp.js --fail-fast
      - store_artifacts:
          path: ~/cko_wp/tests/screenshots
          destination: Failed-Tests


