version: 2

jobs:
  build:
    docker:
      - image: johnnyshrewd/cli:2
    working_directory: ~/cko_wp
    steps:
      - checkout
      - run:
          name: Refresh Wordpress and Install Checkout
          command: |
            sudo service apache2 restart && sudo service mysql restart
      - run:
          name: Install dependencies
          command: |
            cd ~/cko_wp/tests && npm i 
      - run:
          name: Run Tests
          command: |
            cd ~/cko_wp/tests && ./node_modules/.bin/chimp config/chimp.js --fail-fast
      - store_artifacts:
          path: ~/cko_wp/tests/screenshots
          destination: Failed-Tests


